// <auto-generated />
namespace C8.eServices.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class refundprocesspasswordadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refundprocesspasswordadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202309120745144_refundprocesspasswordadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
