// <auto-generated />
namespace C8.eServices.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initmig2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initmig2));
        
        string IMigrationMetadata.Id
        {
            get { return "202511260550587_initmig2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
