// <auto-generated />
namespace C8.eServices.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initmig34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initmig34));
        
        string IMigrationMetadata.Id
        {
            get { return "202605220446274_initmig34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
