IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_accept_property') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_accept_property', 'Message Sent From System To Applicannt', 'You have accepted the property available for Ref: {0}, a deposit of {R} is required. Please login for more Info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_acceptance_letter_submit') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_acceptance_letter_submit', 'Message Sent From System To Applicant', 'You have submited Acceptance letter for Ref: {0}. Please login and action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_agreement_renewal_accepted_by_leasee') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_agreement_renewal_accepted_by_leasee', 'Message Sent From System To Applicant', 'You have accepted agreement renewal for your agreement with reference number {0}. Please contact officials for more info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_agreement_renewal_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_agreement_renewal_approved', 'Message Sent From BO To Applicant', 'Agreement of Lease Renewal Has Been Approved for your application with the reference {0}. Your Renewal OTP is <b>{1}</b>, to be used for actioning the renewal. Please Login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_agreement_renewal_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_agreement_renewal_rejected', 'Message Sent From BO To Applicant', 'Agreement of Lease Renewal Has Been Rejected for your application with the reference {0}. Please contact your officials for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_agreement_renewal_rejected_by_leasee') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_agreement_renewal_rejected_by_leasee', 'Message Sent From System To Applicant', 'You have rejected agreement renewal for your agreement with reference number {0}. Please contact officials for more info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_agreement_renewal_upload_') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_agreement_renewal_upload_', 'Message Sent From BO To Applicant', 'Agreement Renewal Documents has been uploaded successfully for reference number {0}, your agreement period has been extented for {1} months due to end on {2}. Please contact officials for more info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_app_fee_approve') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_app_fee_approve', 'Message Sent From BO To Applicant', 'Application Fee payment has been validated as reflecting for your application with reference no {0}. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_app_fee_reject') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_app_fee_reject', 'Message Sent From BO To Applicant', 'Application Fee has been validated as not-reflecting for your application with reference no {0}. Please login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_applicant_capture_application') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_applicant_capture_application', 'Message Sent From System To Applicant', 'You have successfully captured your application, it is currently {0} status, Reference Number: {1}. Please Login and action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_applicant_generate_debit_order') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_applicant_generate_debit_order', 'Message Sent From System To Applicannt', 'Please note Debit order authority form has been generated for Reference Number:  {0}. Please Login and action before {1}.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_applicant_renewal') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_applicant_renewal', 'Message Sent From BO To Applicannt', 'Your application with Ref: {0}, is due for renewal in the next 3 months. Please login to action before the {date} or your application will proceed to the following step with your action as DID NOT RESPOND.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_Application_payment_uploaded') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_Application_payment_uploaded', 'Message Sent From BO To Applicant', 'Please pay the R250 application fee via EFT using the details below:\nBank: ABSA\nAcc name: GREATER GERMISTON HOUSING CORP PHASE 2\nAcc no: 4052348660\nReg: 2000/007937/07\nBranch: PRESIDENT GERMISTON\nCode: 334542\nSWIFT: ABSAZAJJ\n\nAfter payment, log in, go to PLM Applications > Inbox, search for reference number {0}, select Upload Application Fee, and upload your proof of payment.
', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_approve_renewal_recommendations') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_approve_renewal_recommendations', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been approved for {1} months renewal period. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_assigned_to_risk_assessment') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_assigned_to_risk_assessment', 'Message Sent From System To Applicant', 'You have successfully uploaded documents for {0}. The application has been moved to {1} status. Please await risk assessment.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_at_matched_to_unit') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_at_matched_to_unit', 'Message Sent From System To Applicant', 'You have a available unit matched to your application with the reference number {0}. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_awaiting_applicants_signature') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_awaiting_applicants_signature', 'Message Sent From Systen To Applicant', 'Your application with Ref: {0} is awaiting signature. Please present yourself at the offices to sign the agreement of lease.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_awaiting_debit_order') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_awaiting_debit_order', 'Message Sent From BO To Applicant', 'Your application with Ref: {0} is awaiting Debit Order Authority. Please login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_awaiting_lease_agreement_on_risk') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_awaiting_lease_agreement_on_risk', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been approved for risk assessment. The application has been placed in the waiting list for available unit offers. You will be notified once matched.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_awaiting_lease_agreement_on_riskppp') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_awaiting_lease_agreement_on_riskppp', 'Message Sent From System To Applicant', 'Congratulations! {0} has been approved for lease agreement. The application has been moved to {1} status. Please wait for lease agreement to be generated.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_backoffice_renewal_') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_backoffice_renewal_', 'Message Sent From System To BO', 'The application with Ref: {0}, assigned to you is due for renewal in the next 3 months. Please login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_bo_approve_debit_order') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_bo_approve_debit_order', 'Message Sent From BO To Applicannt', 'Please note Debit order authority form you submited has been approved for Reference Number:  {0}. Please Login and action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_bo_generate_lease_agreement') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_bo_generate_lease_agreement', 'Message Sent From BO To BO', 'Lease agreement generated for your application with reference Number: {1}. Please Login and action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_deactivate_records') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_deactivate_records', 'Message Sent From System To Applicant', 'Reference No: {0} <br/> Application ID: {Id} <br/> Lease Details ID: {Id2}', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_debit_order_register') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_debit_order_register', 'Message Sent From System To Applicannt', 'You have captured debit order on the following Application Ref: {0}. ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_debit_order_register_re') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_debit_order_register_re', 'Message Sent From System To Applicannt', 'You have re-captured debit order on the following Application Ref: {0}. ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_debit_order_reject_bo') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_debit_order_reject_bo', 'Message Sent From BO To Applicannt', 'The debit order for Ref: {0} has been rejected. Please login to the system for more Info and re-capture.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_deposite_approve') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_deposite_approve', 'Message Sent From BO To Applicant', 'Deposit payment has been validated as reflecting for your application with reference no {0}. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_deposite_reject') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_deposite_reject', 'Message Sent From BO To Applicant', 'Deposit payment has been validated as not-reflecting for your application with reference no {0}. Please login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_eviction_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_eviction_approved', 'Message Sent From BO To Applicant', 'Reference No: {0} <br/>Your application has been approved for eviction. For more information please contact property Letting Officer.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_in_to_waiting_list_queue') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_in_to_waiting_list_queue', 'Message Sent From BO To Applicant', 'You have been placed in a waiting list for the application with the reference number {0}, you will be notified once there is available unit matched. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_invite_tenant_for_training') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_invite_tenant_for_training', 'Message Sent From BO To Applicant', 'You have been invited for training for {0} on {date} at {venue}{add}. Please contact Letting Officer for further  Infomation.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_lease_signing_expired') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_lease_signing_expired', 'Lease Signing Expired Notification', 'BR19: Notification sent to the tenant when the 30-day lease signing deadline has expired and the application is disregarded.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_first_eviction') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_first_eviction', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} is being evicted. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_risk_reject') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_risk_reject', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been rejected for risk assessment.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_risk_reject_documents') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_risk_reject_documents', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been rejected for risk assessment due to incorrect documents submitted. Reason: {1}', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_risk_reject_unaffordability') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_risk_reject_unaffordability', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been rejected for risk assessment due to unaffordability. Reason: {1}', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_tenant_notice_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_tenant_notice_approved', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been approved for termination. For more information please contact your Letting Officer.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_tenant_notice_reject') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_tenant_notice_reject', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been rejected for termination, you will not be terminating before initial date issued.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_termination_accepted') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_termination_accepted', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} will be terminating new date has been issued. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_on_termination_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_on_termination_rejected', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} will be not terminated on requested date. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_re_list_to_queue') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_re_list_to_queue', 'Message Sent From System To Applicant', 'You have re-listed your application with Ref: {0} in a waiting list, you will be notified once matched to a unit. For more infomation contact your officials.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_reject_property') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_reject_property', 'Message Sent From Sysytem To Applicannt', 'You have rejected the property that was availed for Ref: {0}. Please login for more Info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_reject_property') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_reject_property', 'Message Sent From System To Applicannt', 'You have rejected the property that was availed for Ref: {0}. Please login for more Info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_rejected_renewal_recommendations') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_rejected_renewal_recommendations', 'Message Sent From BO To Applicant', 'Your application with the reference number {0} has been rejected for renewal it will terminate. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_remove_from_queue') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_remove_from_queue', 'Message Sent From System To Applicant', 'You have removed your application with Ref: {0} from the waiting list. For more infomation contact your officials.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_renewal_reject_by_customer') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_renewal_reject_by_customer', 'Message Sent From BO To Applicant', 'The renewal offer sent by Back Office to applicant has been rejected by applicant, application with the reference number {0}, Reason: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_rental_escalation_msg') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_rental_escalation_msg', 'Message Sent From System To Applicant', 'Rental amount has been increased for the unit leased to <b>R{0}<b/> as per clause 6.3 Annual Rental Increase of the agreement of lease. Please contact officials for more infomation.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_request_slots') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_request_slots', 'Message Sent From System To Applicant', 'You have requested for additional time slots, for your application with reference number {0}. For more information, please login.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_serve_notice') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_serve_notice', 'Message Sent From System To Applicant', 'You have served notice for terminating application with reference no: {0} on {1}. Please wait for your relavent Letting Officer to action your notice.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_service_termination_reminder') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_service_termination_reminder', 'Message Sent From System To Applicant', 'Your lease application with Ref: {0}, is due for termination on {date}. Contact your housing supervisor for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_service_unmatch_not_actioned') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_service_unmatch_not_actioned', 'Message Sent From System To Applicant', 'Your application with Ref: {0}, has been un-matched a unit due to nonacceptance for 30 days. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_successful_agreement_transfer') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_successful_agreement_transfer', 'Message Sent From BO To Applicant', 'Agreement of lease has been transferred successfully to {1} {2} for your application with Ref: {0}. Please contact your Housing Liason Officer for more infomation.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_unit_accepted_deposit_payment_details') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_unit_accepted_deposit_payment_details', 'Unit Accepted - Deposit Payment Details', 'You have successfully accepted the unit offer. Please make payment for the deposit using the following banking details: Bank Name: Standard Bank, Account Name: Ekurhuleni Metropolitan Municipality, Account Number: 001844075, Branch Code: 011545, Reference: {0}. After making payment, please login to the system and upload your proof of payment.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_unit_ispection_at_applicant_confirm') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_unit_ispection_at_applicant_confirm', 'Message Sent From System To Applicant', 'You have scheduled {0} for Unit Inspection, please avail on {date} at {time} for inspection.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_unit_ispection_mail') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_unit_ispection_mail', 'Message Sent From BO To Applicant', 'Your application with Ref: {0} is due for Unit Inspection. Please login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_unit_offer_expired') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_unit_offer_expired', 'Unit Offer Expired Notification', 'BR09: Notification sent to the applicant when the 30-day unit acceptance deadline has expired. The unit offer is withdrawn and the applicant re-listed on the waiting list.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_up_for_renewal') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_up_for_renewal', 'Message Sent From System To Applicant', 'Your application with the reference number {0} is due for renewal, it currently under renewal review. Please login for more information.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_update_refund_response_norefund_due') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_update_refund_response_norefund_due', 'Update Refund Response No Refund Due', 'Dear tenant, please note that you will not be receiving any deposit refund, or you will be receiving a partial refund due to the ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_update_refund_response_refund_due') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_update_refund_response_refund_due', 'Update Refund Response RefundDue', 'Dear Tenant, please note that there is a refund due for your deposit and the money should appear in your account in the next 21 days.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_waiting_list_reentry') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_waiting_list_reentry', 'Message Sent From System To Applicant', 'Waiting list period about to lapse for your application with reference no {0}, indicate if unit is still required. Please login to action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_waiting_list_remove_on_reject') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_waiting_list_remove_on_reject', 'Message Sent From System To Applicannt', 'Your Application has been removed from the waiting list queue for Ref: {0} after you rejected 2 properties. Please login for more Info.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'plm_warning_letter_msg') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('plm_warning_letter_msg', 'Email Warning Letter', 'Warning letter has been sent to you, please log into the system to view your letter.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_bo_new_case_loaded') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_bo_new_case_loaded', 'Message Sent From System To BO', 'Please note a new case has been allocated to your {0} queue, Reference Number: {1}. Please Login and action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_bo_new_case_redistributed') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_bo_new_case_redistributed', 'Message Sent From System To BO', 'Please note a new case has been re-allocated to your {0} queue, Reference Number: {1}. Please Login and action.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_bo_sends_new_message') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_bo_sends_new_message', 'Message Sent From BO', '
A Message has been sent by Back Office on your RCS application. 
Please login to the RCS System to view the message,
This can be done by logging in and searching for RCS Application with Reference Number: {1} and clicking on the "Message" Button.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_bo_sends_new_message_to_bo') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_bo_sends_new_message_to_bo', 'Message Sent From BO To BO', '
A Message has been sent from Back Office on a case that you are currently assigned. 
Please login to the RCS System to view the message,
This can be done by logging in and searching for RCS Application with Reference Number: {1} and clicking on the "Message" Button.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_conveyancer_sends_new_message') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_conveyancer_sends_new_message', 'Message Sent From Conveyancer', '
A Message has been sent from the Conveyancer to Back Office on a case that you are currently assigned. 
Please login to the RCS System to view the message,
This can be done by logging in and searching for RCS Application with Reference Number: {1} and clicking on the "Message" Button.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_Application_payment_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_Application_payment_approved', 'RCS application fee has been verified', 'Your proof of payment documents for RCS application fee has been verified for Application Reference Number: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_Application_payment_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_Application_payment_rejected', 'RCS application fee has been rejected', 'Your proof of payment documents for RCS application fee has been rejected , please re-upload required documents for RCS Application Reference Number:  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_Assessment_payment_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_Assessment_payment_approved', 'proof of payment documents for RCS assesment figures has been verified ', 'Your proof of payment documents for RCS assesment figures has been verified for Application Reference Number: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_Assessment_payment_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_Assessment_payment_rejected', 'proof of payment documents for RCS assessment figures has been rejected ', ' Your proof of payment documents for RCS assessment figures has been rejected , please re-upload required documents for RCS Application Reference Number: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_Assessment_Uploaded') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_Assessment_Uploaded', 'view your assessment figures', 'Rates Clearance figures sent, please login to your RCS application and view your assessment figures. ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_assessment_uploaded_figures_fully_paid') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_assessment_uploaded_figures_fully_paid', 'Assessment Figures Fully Paid With Account Credit', 'Due to municipal account in credit, assessment figures payment is fully paid, RCS Application will be sent to rates clearance clerk for validation.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_captured_successfully') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_captured_successfully', 'Property Lease Application has been captured successfully', 'Your Property Lease Application has been captured successfully your Reference Number is :  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_documents_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_documents_approved', 'Documents Approved', 'Your Documents have been approved for RCS Application Reference Number:  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_documents_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_documents_rejected', 'Documents have been been Rejected', 'Your Documents have been been Rejected, please re-upload application documents for RCS Application Reference Number:  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_rcc_issued') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_rcc_issued', 'Rates clearance certificate issued', 'Rates clearance certificate issued for application number:   ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_refund_bank') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_refund_bank', 'Refund Paid To Conveyancer Bank Account', 'Rates Clearance Clerk Processed Refund, Refund Paid To Conveyancer Bank Account. RCS Refund Application Reference Number:  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_refund_collection') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_refund_collection', 'Refund Ready For Collection', 'Rates Clearance Clerk Processed Refund, Refund Ready For Collection. RCS Refund Application Reference Number:  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_refund_docs_approved') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_refund_docs_approved', ' Documents have been approved for RCS Refund', 'Your Documents have been approved for RCS Refund Application Reference Number: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_refund_docs_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_refund_docs_rejected', 'Documents have been been Rejected Refund', 'Your Documents have been been Rejected, please re-upload documents for RCS Refund Application Reference Number: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_refund_pop_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_refund_pop_rejected', 'Refund Proof of Payemnt Rejected Email', 'Your Documents have been been Rejected, please re-upload Proof of Payment for RCS Refund Application Reference Number:  ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_email_refund_rejected') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_email_refund_rejected', 'Refund Application Has Been Rejected', 'Your Refund Application Has Been Rejected, RCS Refund Application Reference Number: ', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_refund_bo_sends_new_message') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_refund_bo_sends_new_message', 'Message Sent From BO', '
A Message has been sent by Back Office on your RCS application. 
Please login to the RCS System to view the message,
This can be done by logging in and searching for Refund Application with Reference Number: {1} and clicking on the "Message" Button.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_refund_bo_sends_new_message_to_bo') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_refund_bo_sends_new_message_to_bo', 'Message Sent From BO To BO', '
A Message has been sent from Back Office on a case that you are currently assigned. 
Please login to the RCS System to view the message,
This can be done by logging in and searching for Refund Application with Reference Number: {1} and clicking on the "Message" Button.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'rcs_refund_conveyancer_sends_new_message') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('rcs_refund_conveyancer_sends_new_message', 'Message Sent From Conveyancer', '
A Message has been sent from the Conveyancer to Back Office on a case that you are currently assigned. 
Please login to the RCS System to view the message,
This can be done by logging in and searching for Refund Application with Reference Number: {1} and clicking on the "Message" Button.', 1, 0, GETDATE()); END
IF NOT EXISTS (SELECT 1 FROM EmailContentTypes WHERE [Key] = 'reallocated_for_assessment') BEGIN INSERT INTO EmailContentTypes ([Key], [Name], [Description], IsActive, IsDeleted, CreatedDateTime) VALUES ('reallocated_for_assessment', 'Dear tenant, please note your application has been re-allocated for risk assessment', 'Dear tenant, please note your application has been re-allocated for risk assessment', 1, 0, GETDATE()); END
