//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.eServices.Mvc.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RCS_ATTORNEYS
    {
        public string Attorney_Code { get; set; }
        public string FirmName { get; set; }
        public string Practice_number { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public string Contact_Number { get; set; }
        public string Email_Address { get; set; }
    }
}
